name: factory_stockapp CI

on:
  push:
    branches: [ lint ]
#  pull_request:
#    branches: [ master ]

jobs:
  build-test:

    runs-on: ubuntu-latest
    if: >-
      ${{ !contains(github.event.head_commit.message, '[ci skip]') &&
      !contains(github.event.head_commit.message, '[skip ci]') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembledebug --stacktrace
      - name: test
        run: |
          ls


#      - name: Build Complete
#        run: echo "Build complete"
#  code-check:
#    needs: build-test
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          token: ${{ secrets.ACCESS_TOKEN }}
#          submodules: true
#
#      - name: set up JDK 11
#        uses: actions/setup-java@v2
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#          cache: gradle
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: lint Code
#        run: ./gradlew lint
#
#      - name: lint file upload
#        uses: actions/upload-artifact@v3
#        with:
#          name: lint-artifact
#          path: app/build/reports/*.html
#        if: success()
#
#      - name: Code Style Check
#        run: ./gradlew checkstyle
#
#      - name: checkstyle file upload
#        uses: actions/upload-artifact@v3
#        with:
#          name: checkstyle-artifact
#          path: app/build/reports/checkstyle/*.html
#        if: success()





